/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_centralnexus_input_Joystick */

#ifndef _Included_com_centralnexus_input_Joystick
#define _Included_com_centralnexus_input_Joystick
#ifdef __cplusplus
extern "C" {
#endif
#undef com_centralnexus_input_Joystick_HAS_Z
#define com_centralnexus_input_Joystick_HAS_Z 1L
#undef com_centralnexus_input_Joystick_HAS_R
#define com_centralnexus_input_Joystick_HAS_R 2L
#undef com_centralnexus_input_Joystick_HAS_U
#define com_centralnexus_input_Joystick_HAS_U 4L
#undef com_centralnexus_input_Joystick_HAS_V
#define com_centralnexus_input_Joystick_HAS_V 8L
#undef com_centralnexus_input_Joystick_HAS_POV
#define com_centralnexus_input_Joystick_HAS_POV 16L
#undef com_centralnexus_input_Joystick_HAS_POV4DIR
#define com_centralnexus_input_Joystick_HAS_POV4DIR 32L
#undef com_centralnexus_input_Joystick_HAS_POVCONT
#define com_centralnexus_input_Joystick_HAS_POVCONT 64L
#undef com_centralnexus_input_Joystick_POV_CENTERED
#define com_centralnexus_input_Joystick_POV_CENTERED -0.01f
#undef com_centralnexus_input_Joystick_POV_FORWARD
#define com_centralnexus_input_Joystick_POV_FORWARD 0.0f
#undef com_centralnexus_input_Joystick_POV_RIGHT
#define com_centralnexus_input_Joystick_POV_RIGHT 90.0f
#undef com_centralnexus_input_Joystick_POV_BACKWARD
#define com_centralnexus_input_Joystick_POV_BACKWARD 180.0f
#undef com_centralnexus_input_Joystick_POV_LEFT
#define com_centralnexus_input_Joystick_POV_LEFT 270.0f
#undef com_centralnexus_input_Joystick_BUTTON1
#define com_centralnexus_input_Joystick_BUTTON1 1L
#undef com_centralnexus_input_Joystick_BUTTON2
#define com_centralnexus_input_Joystick_BUTTON2 2L
#undef com_centralnexus_input_Joystick_BUTTON3
#define com_centralnexus_input_Joystick_BUTTON3 4L
#undef com_centralnexus_input_Joystick_BUTTON4
#define com_centralnexus_input_Joystick_BUTTON4 8L
#undef com_centralnexus_input_Joystick_BUTTON5
#define com_centralnexus_input_Joystick_BUTTON5 16L
#undef com_centralnexus_input_Joystick_BUTTON6
#define com_centralnexus_input_Joystick_BUTTON6 32L
#undef com_centralnexus_input_Joystick_BUTTON7
#define com_centralnexus_input_Joystick_BUTTON7 64L
#undef com_centralnexus_input_Joystick_BUTTON8
#define com_centralnexus_input_Joystick_BUTTON8 128L
#undef com_centralnexus_input_Joystick_BUTTON9
#define com_centralnexus_input_Joystick_BUTTON9 256L
#undef com_centralnexus_input_Joystick_BUTTON10
#define com_centralnexus_input_Joystick_BUTTON10 512L
#undef com_centralnexus_input_Joystick_BUTTON11
#define com_centralnexus_input_Joystick_BUTTON11 1024L
#undef com_centralnexus_input_Joystick_BUTTON12
#define com_centralnexus_input_Joystick_BUTTON12 2048L
#undef com_centralnexus_input_Joystick_BUTTON13
#define com_centralnexus_input_Joystick_BUTTON13 4096L
#undef com_centralnexus_input_Joystick_BUTTON14
#define com_centralnexus_input_Joystick_BUTTON14 8192L
#undef com_centralnexus_input_Joystick_BUTTON15
#define com_centralnexus_input_Joystick_BUTTON15 16384L
#undef com_centralnexus_input_Joystick_BUTTON16
#define com_centralnexus_input_Joystick_BUTTON16 32768L
#undef com_centralnexus_input_Joystick_BUTTON17
#define com_centralnexus_input_Joystick_BUTTON17 65536L
#undef com_centralnexus_input_Joystick_BUTTON18
#define com_centralnexus_input_Joystick_BUTTON18 131072L
#undef com_centralnexus_input_Joystick_BUTTON19
#define com_centralnexus_input_Joystick_BUTTON19 262144L
#undef com_centralnexus_input_Joystick_BUTTON20
#define com_centralnexus_input_Joystick_BUTTON20 524288L
#undef com_centralnexus_input_Joystick_BUTTON21
#define com_centralnexus_input_Joystick_BUTTON21 1048576L
#undef com_centralnexus_input_Joystick_BUTTON22
#define com_centralnexus_input_Joystick_BUTTON22 2097152L
#undef com_centralnexus_input_Joystick_BUTTON23
#define com_centralnexus_input_Joystick_BUTTON23 4194304L
#undef com_centralnexus_input_Joystick_BUTTON24
#define com_centralnexus_input_Joystick_BUTTON24 8388608L
#undef com_centralnexus_input_Joystick_BUTTON25
#define com_centralnexus_input_Joystick_BUTTON25 16777216L
#undef com_centralnexus_input_Joystick_BUTTON26
#define com_centralnexus_input_Joystick_BUTTON26 33554432L
#undef com_centralnexus_input_Joystick_BUTTON27
#define com_centralnexus_input_Joystick_BUTTON27 67108864L
#undef com_centralnexus_input_Joystick_BUTTON28
#define com_centralnexus_input_Joystick_BUTTON28 134217728L
#undef com_centralnexus_input_Joystick_BUTTON29
#define com_centralnexus_input_Joystick_BUTTON29 268435456L
#undef com_centralnexus_input_Joystick_BUTTON30
#define com_centralnexus_input_Joystick_BUTTON30 536870912L
#undef com_centralnexus_input_Joystick_BUTTON31
#define com_centralnexus_input_Joystick_BUTTON31 1073741824L
#undef com_centralnexus_input_Joystick_BUTTON32
#define com_centralnexus_input_Joystick_BUTTON32 -2147483648L
#undef com_centralnexus_input_Joystick_AXIS_TOTAL
#define com_centralnexus_input_Joystick_AXIS_TOTAL 7L
#undef com_centralnexus_input_Joystick_AXIS_X
#define com_centralnexus_input_Joystick_AXIS_X 0L
#undef com_centralnexus_input_Joystick_AXIS_Y
#define com_centralnexus_input_Joystick_AXIS_Y 1L
#undef com_centralnexus_input_Joystick_AXIS_Z
#define com_centralnexus_input_Joystick_AXIS_Z 2L
#undef com_centralnexus_input_Joystick_AXIS_R
#define com_centralnexus_input_Joystick_AXIS_R 3L
#undef com_centralnexus_input_Joystick_AXIS_U
#define com_centralnexus_input_Joystick_AXIS_U 4L
#undef com_centralnexus_input_Joystick_AXIS_V
#define com_centralnexus_input_Joystick_AXIS_V 5L
#undef com_centralnexus_input_Joystick_AXIS_POV
#define com_centralnexus_input_Joystick_AXIS_POV 6L
/*
 * Class:     com_centralnexus_input_Joystick
 * Method:    getNumDevices
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_centralnexus_input_Joystick_getNumDevices
  (JNIEnv *, jclass);

/*
 * Class:     com_centralnexus_input_Joystick
 * Method:    isPluggedIn
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_centralnexus_input_Joystick_isPluggedIn
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_centralnexus_input_Joystick
 * Method:    poll
 * Signature: (I[F)I
 */
JNIEXPORT jint JNICALL Java_com_centralnexus_input_Joystick_poll
  (JNIEnv *, jclass, jint, jfloatArray);

/*
 * Class:     com_centralnexus_input_Joystick
 * Method:    getCapabilities
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_centralnexus_input_Joystick_getCapabilities
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_centralnexus_input_Joystick
 * Method:    getNumButtons
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_centralnexus_input_Joystick_getNumButtons
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_centralnexus_input_Joystick
 * Method:    getNumAxes
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_centralnexus_input_Joystick_getNumAxes
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_centralnexus_input_Joystick
 * Method:    toString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_centralnexus_input_Joystick_toString
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
