
TARGET1 = robo1

TARGET2 = robo2

#COMMON_OBJS1 = ports.o wdog.o serial.o parallel.o dm3gx1.o pwm.o leds.o
COMMON_OBJS1 = ports.o wdog.o adc.o serial.o dm3gx1.o minia.o pwm.o leds.o

#COMMON_OBJS2 = ports.o wdog.o adc.o parallel.o bmu09a.o lsm215.o minia.o leds.o
COMMON_OBJS2 = ports.o wdog.o parallel.o bmu09a.o lsm215.o leds.o

include Rules.mk

